[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_egui = "0.25"
egui = "0.26"
egui_plot = "0.26"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
